### ISSUE TITLE
Be Guava 19 compatible

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#185]
As Xtext Xpect should work with Guava 19. It at least does not regarding the use of Closables.closeQuietly since this method is different in different guava versions

**Comment by dhuebner** [comment]
The same with guava 18 from Neon SR3

**Comment by cdietrich** [comment]
MoreObjects.ToStringHelper now replaces Objects.ToStringHelper

**Comment by cdietrich** [comment]
the main problem is that the new method is not available with versions < guava 18
thus i wonder if we should pin the guava versions to 21.
unfortunately the tps seem to be quite old, so i dont know which ones are actually used

**Comment by cdietrich** [comment]
=> at the specific place we can replace the dependency with an xtext own class.
(am now sure how it differs)

**Comment by cdietrich** [comment]
done with https://github.com/eclipse/Xpect/commit/b9de31164e7cc31329cd7160d44e7493d223e76a
