### ISSUE TITLE
RunWith class not found

### ISSUE THREAD

**Issue by magick93** [eclipse/Xpect#235]
Hello
I installed xpect using eclipse update site http://www.xpect-tests.org/updatesite/nightly/

I then added dependencies to my project:
```
 org.xpect;bundle-version="0.2.0",
 org.xpect.xtext.lib;bundle-version="0.2.0",
 org.xpect.ui.junit;bundle-version="0.2.0",
 org.xpect.xtext.xbase.lib;bundle-version="0.2.0"
```

But when I try to write a test, eclipse complains about the following:

![screenshot from 2018-06-03 19-17-01](https://user-images.githubusercontent.com/2173213/40884182-436a4b7a-6763-11e8-8153-66e60714a2ad.png)

**Comment by cdietrich** [comment]
In xtend the type literal is XpectRunner or typeof(XpectRunner) and not XpectRunner.class

**Comment by magick93** [comment]
Thanks @cdietrich
