### ISSUE TITLE
Dependency jrunner can no longer be resolved

### ISSUE THREAD

**Issue by wegendt-bosch** [eclipse/Xpect#263]
I can no longer resolve my target platform with this:

```xml
<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
<unit id="org.xpect.sdk.feature.group" version="0.2.0.201706301756"/>
<repository location="http://www.xpect-tests.org/updatesite/nightly/"/>
</location>
```
(https://github.com/eclipse/mita/blob/master/bundles/org.eclipse.mita.target/oxygen.target)

The error message is:
`Missing requirement: Xpect SDK Feature ... requires 'org.eclipse.jdt.jrunners 0.0.0' but it could not be found`

Is this an issue with Xpect, my setup or the eclipse infrastructure?

**Comment by cdietrich** [comment]
this seems to be specific to your infrastructure.
maybe github pages had an outage ....

**Comment by wegendt-bosch** [comment]
Ok, thanks for the feedback!
