### ISSUE TITLE
Xpect files cannot be launched in IDE under Java 9

### ISSUE THREAD

**Issue by mor-n4** [eclipse/Xpect#264]
When using Java 9 or later, Xpect files can no longer be executed in the Eclipse IDE by right-clicking them and selecting `Run as / JUnit Test`.

The reason for this is that class `ClasspathUtil` is casting the system class loader to `URLClassLoader` but as of JDK9 the system class loader is no longer a subtype of that class, cf. https://blog.codefx.org/java/java-9-migration-guide/#Casting-To-URL-Class-Loader.

**Comment by cdietrich** [comment]
@mor-n4 in Xtext 2.18+ we use classgraph for that (orbit is still in the make)

**Comment by mor-n4** [comment]
Thanks for the info! I have found another solution that parses system property `java.class.path` in the same way as the old system class loader did and also the new Java 9 system class loader is still doing (not much code). We could use that as an intermediate fix until we switch Xpect to classgraph.
