### ISSUE TITLE
Update site broken

### ISSUE THREAD

**Issue by Guite** [eclipse/Xpect#275]
Now after Jenkins was down for a few days it is running again.
The artifacts seem not working yet though.

- Looking at https://ci.eclipse.org/xpect/job/Xpect/job/master/19/ no artifacts link is shown.
- Direct call of https://ci.eclipse.org/xpect/job/Xpect/job/master/lastSuccessfulBuild/artifact/org.eclipse.xpect.releng/p2-repository/target/repository/ results in a 403 error.

**Comment by cdietrich** [comment]
we had similar issues with Xtext in the past. The Eclipse infrastructure s...s in this respect. the only thing that helped is to restart the jobs. this can be done by a committer only

**Comment by mmews-n4** [comment]
For future reference: This is a follow-up of https://bugs.eclipse.org/bugs/show_bug.cgi?id=561808

**Comment by dhuebner** [comment]
@Guite We will need to fix our jenkins setup. This will take time.

For those how need a working target platform in his project **now** could try `https://ci.eclipse.org/xpect/job/Xpect/job/release_0.2.0/lastBuild/artifact/org.eclipse.xpect.releng/p2-repository/target/repository/`

**Comment by Guite** [comment]
@dhuebner thank you

**Comment by cdietrich** [comment]
https://download.eclipse.org/xpect/updates/nightly/latest/ is back
