### ISSUE TITLE
Repair OOmph

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#330]
would be nice to have a working oomph
that picks up the target file like in Xtext
cc @tjeske

**Comment by merks** [comment]
It just so happens that I'm working on the following:

![image](https://github.com/eclipse/Xpect/assets/208716/78c04bd6-1078-4609-8a4c-eee5654a72ac)

It's really hard to get an error free workspace otherwise!

I'll soon be ready to contribute this...

**Comment by merks** [comment]
My fork's main branch has a link to the new setup:

https://github.com/merks/Xpect/blob/master/CONTRIBUTING.md

Currently this will clone my fork.  The setup does a Maven/Tycho build to generate all the models, and then has a targlet to import all the projects and setup a target platform with the latest of everything in it.  I tried to reduce the number of warnings:

![image](https://github.com/eclipse/Xpect/assets/208716/7f1ea078-fcea-4d3f-aaf0-4ed50fe89002)

You should be able to try this locally if you wish...  Be sure to let it clone my fork...

**Comment by cdietrich** [comment]
done. thx @merks
