### ISSUE TITLE
Nightly does not work anymore

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#350]
[INFO]       (you can configure this with -Dtycho.p2.transport.min-cache-minutes=<desired minimum cache duration>)
[INFO] Adding repository https://download.eclipse.org/releases/2023-09
[INFO] Adding repository https://download.eclipse.org/justj/tools/updates/nightly/latest
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.justj.p2 0.1.0.v20240522-0710
[ERROR]   Missing requirement: org.eclipse.justj.codegen 0.1.0.v20240802-1045 requires 'osgi.bundle; org.apache.commons.commons-io [2.16.1,3.0.0)' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.justj.p2 0.1.0.v20240522-0710 depends on: osgi.bundle; org.eclipse.justj.codegen 0.0.0
[ERROR] 

@merks does this ring a bell?

**Comment by merks** [comment]
Yes, sorry.   😢 

Building JustJ JREs was failing with strange missing package dependencies so I forced the latest version of the bundle with those requirements.  

Change this line:

https://github.com/eclipse/Xpect/blob/adf2b741aa97a2e0eec6c8986e1ddc8da40ac77b/pom.xml#L25

to this:

https://download.eclipse.org/releases/latest

I had the same failure in BIRT and did this:

https://github.com/eclipse-birt/birt/commit/758539781bcf0370d4669d92bdab56ab8956bec9

**Comment by cdietrich** [comment]
@merks can i also use 2024-06
does latest still work with java 17?

**Comment by merks** [comment]
Currently yes.  Whether that will say true is another question.  Using Java 21 now should work too.

**Comment by cdietrich** [comment]
i dont know what of the rest works with j21. so i want to postpone moving to 21

**Comment by merks** [comment]
Note that you can use Java 21 only for the promotion step without affecting any other part of the build:

https://github.com/eclipse/Xpect/blob/d3227f0a1150c7bb194ef802bc171b86c122173f/org.eclipse.xpect.releng/promotion/pom.xml#L33
