### ISSUE TITLE
Investigate and fix failing tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#353]
[JvmModel.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/jvmmodelinferrer.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/JvmModel.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_jvmmodelinferrer/___/)
    [JvmSignatures.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/jvmmodelinferrer.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/JvmSignatures.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_jvmmodelinferrer/___/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/linking.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_linking/___/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/parser.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_parser/___/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/resourcedescription.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_resourcedescription/___/)
    [generateOneFile.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/generator.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/generateOneFile.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_generator/___/)
    [generateTwoFiles1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/generator.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/generateTwoFiles1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_generator/___/)
    [generateTwoFiles2.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/generator.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/generateTwoFiles2.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_generator/___/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/scoping.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_scoping/___/)
    [CombiningMultipleTests.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/testsuite.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/CombiningMultipleTests.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_testsuite/___/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/validation.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_validation/___/)
    [generateOneFile.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/generator.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/generateOneFile.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_generator/____2/)
    [generateTwoFiles1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/generator.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/generateTwoFiles1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_generator/____2/)
    [generateTwoFiles2.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/generator.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/generateTwoFiles2.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_generator/____2/)
    [JvmModel.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/jvmmodelinferrer.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/JvmModel.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_jvmmodelinferrer/____2/)
    [JvmSignatures.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/jvmmodelinferrer.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/JvmSignatures.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_jvmmodelinferrer/____2/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/linking.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_linking/____2/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/parser.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_parser/____2/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/resourcedescription.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_resourcedescription/____2/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/scoping.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_scoping/____2/)
    [CombiningMultipleTests.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/testsuite.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/CombiningMultipleTests.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_testsuite/____2/)
    [test1.dmodel.xt: src/org/eclipse/xtext/example/domainmodel/xpect/tests/validation.(?)](https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/testReport/junit/test1.dmodel/xt_%20src_org_eclipse_xtext_example_domainmodel_xpect_tests_validation/____2/)

https://ci.eclipse.org/xpect/job/Xpect/job/master/1078/#showFailuresLink

**Comment by cdietrich** [comment]
@lorenzobettini @szarnekow does this ring any bells?

**Comment by cdietrich** [comment]
@iloveeclipse were there any changes in jdt that could cause this?

**Comment by iloveeclipse** [comment]
@cdietrich : as Ed already mentioned, there is a change in internal JDT code that affects Xtext, see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2753

Part of `XbaseUIValidator` code is a copy (why???) from `org.eclipse.jdt.internal.core.PackageFragmentRoot.getResolvedClasspathEntry()`.

**Original**
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/57bcdfca1de248b39e857d3e08021b00c7a3c80f/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/PackageFragmentRoot.java#L624-L633

**Copy**
https://github.com/eclipse/xtext/blob/87b6681c980013cf1bc4a6cfc705f330de3b1d07/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/XbaseUIValidator.java#L221-L233

So I would recommend to replace this part in XbaseUIValidator with original code from JDT.

**Comment by cdietrich** [comment]
@iloveeclipse and what is the proper code to be used in xbase

**Comment by iloveeclipse** [comment]
> @iloveeclipse and what is the proper code to be used in xbase

The original code in `PackageFragmentRoot.getResolvedClasspathEntry()`. What's wrong with that, why should it be copied?

**Comment by cdietrich** [comment]
+	/*
+	 * JDT 3.6 or later could use root.getResolvedClasspathEntry, but that was not available in 3.5
+	 * Therefore we inline the implementation here but avoid throwing an exception in case there is no entry
+	 */

**Comment by cdietrich** [comment]
@szarnekow is there any other reason to keep this.
i also wonder why comment was removed

**Comment by cdietrich** [comment]
<img width="1036" alt="grafik" src="https://github.com/user-attachments/assets/a361d861-21c0-426a-aa1a-85e315fc5e90">

**Comment by cdietrich** [comment]
the original jdt code does not seem to have had the double fallback with 

root.getPath() and root.getJavaProject().getPath()

**Comment by iloveeclipse** [comment]
Just in case the old code did really something that was needed, you could use `org.eclipse.jdt.internal.core.JavaModelManager.PerProjectInfo.getRootPathToResolvedEntries()` which will return same map.

The problem is, which is why I don't like to revert the code, that `JavaModelManager.PerProjectInfo` is a very bad data structure with **public not final fields**, which shouldn't be written like this at all in the first place, despite being used from non JDT code. 
So I would ask first just use `PackageFragmentRoot.getResolvedClasspathEntry()` and only if it is not sufficient use other internal JDT code.

**Comment by cdietrich** [comment]
unfortunately the commit has no test
so hard to tell what will break.

unfortunately i have no time to investigate the next days

**Comment by cdietrich** [comment]
pushed two experimental branches to xtext

**Comment by cdietrich** [comment]
AccessRestrictionInWorkspaceTest fails when just delegating

**Comment by cdietrich** [comment]
result good case
/firstProject[CPE_PROJECT][K_SOURCE][isExported:false][AccessRuleSet {pattern=allowed/* (ACCESSIBLE), pattern=discouraged/* (DISCOURAGED), pattern=**/* (NON ACCESSIBLE | IGNORE IF BETTER)} [classpath entry: firstProject]][combine access rules:true]

result bad case
/firstProject/src[CPE_SOURCE][K_SOURCE][isExported:false]

**Comment by iloveeclipse** [comment]
> result good case /firstProject[CPE_PROJECT][K_SOURCE][isExported:false][AccessRuleSet {pattern=allowed/* (ACCESSIBLE), pattern=discouraged/* (DISCOURAGED), pattern=**/* (NON ACCESSIBLE | IGNORE IF BETTER)} [classpath entry: firstProject]][combine access rules:true]
> 
> result bad case /firstProject/src[CPE_SOURCE][K_SOURCE][isExported:false]

Could you point to the source & test result?
Just wondering if the test does what can actually happen or simply its own "extension" that returns something that JDT would not return for a **package** but for a **project**? I mean, is the method misused to do two things?

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/actions/runs/10264301955
(ci.eclipse.org is still running)
the test is at
/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/validation/AccessRestrictionInWorkspaceTest.xtend

i just see there is multiple projects involved but have no clue what the purpose of the code is.
the method has a project and a root.

```
XtendUIValidator(XbaseUIValidator).getResolvedClasspathEntry(IJavaProject, IPackageFragmentRoot) line: 225	
XtendUIValidator(XbaseUIValidator).computeRestriction(IJavaProject, IType) line: 196	
XtendUIValidator(XbaseUIValidator).checkRestrictedType(EObject, EStructuralFeature, JvmDeclaredType) line: 158	
XtendUIValidator(XbaseUIValidator).checkRestrictedType(JvmTypeReference) line: 118	
```

i remember the jdt associates stuff to the "first" project but this is just a very very vague remembering
maybe @szarnekow knows more

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/xtext/job/cd-jdt-resolved-classpath-entry-2/2/#showFailuresLink
