### ISSUE TITLE
Fix Commons logging build problem

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#361]
Proposal:

add the new bundle to both target platforms and adjust build.properties files

**Comment by cdietrich** [comment]
cc @mehmet-karaman

**Comment by mehmet-karaman** [comment]
With new bundle you mean the jdt xtext facade project?

**Comment by cdietrich** [comment]
No the new bundle name for commons logging 
Check mwe or xtext repo

**Comment by mehmet-karaman** [comment]
Ok, i am going to try this.

**Comment by mehmet-karaman** [comment]
started maven build against the two targets in my workspace.. it built succesfully, so are you sure we have to change this?

**Comment by cdietrich** [comment]
the one against "latest"?

**Comment by cdietrich** [comment]
i wonder if there is something cached in your local maven repo that is used

**Comment by cdietrich** [comment]
still failing @mehmet-karaman 
does it work on your companys replica of the build?

**Comment by mehmet-karaman** [comment]
Now it fails also on our replica build.. I've used the full-build.sh file for building.. I didn't checked where we get our dependencies, might be that this repo still had this repository where this old bundle was available.

**Comment by mehmet-karaman** [comment]
I think I can continue from this.. I will create a PR when its finished.. Thanks..
