### ISSUE TITLE
With Xtext and MWE going to 2024-03 as minimal tp and J17 we should follow

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#365]
With Xtext and MWE going to 2024-03 as minimal tp and J17 we should follow

@mehmet-karaman maybe you can find some time.

for the J17 part check what was done in the MWE and Xtext repos

**Comment by mehmet-karaman** [comment]
@cdietrich the Java 17 part is done.. Please check if it contains all known places.. The platform 2024-03 changes will follow.

**Comment by mehmet-karaman** [comment]
I've a few questions on the min. platform and min. xtext tp task:
- Xpect bases still on xtext 2.14.0, should we update also this to 2.34? 
- Why do we have version names in project names? Why we don't name them minimal_eclipse_xtext instead of eclipse_2023_03-xtext_2_31_0 and eclipse-xtext_nightly instead of eclipse_2024_06-xtext_nightly ?

**Comment by cdietrich** [comment]
- i dont think there is a specific reason for version names. => renaming is a good idea. may we also can put them just into the root folder as in xtext repo.
- yes 2.34 / mwe 1.11/2.17 would be ok

**Comment by mehmet-karaman** [comment]
Why does the Xtext 202403.target use this repo? https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2025-03
Shouldn't it be using the 2024-03 one? Shall I use the same?

**Comment by cdietrich** [comment]
No idea. I guess just stupid search and replace
Maybe it should work without orbit at all too

**Comment by mehmet-karaman** [comment]
@cdietrich do we have a script or something which sets these bundle-version=".." automatically? Or are we doing this manually? Because the Eclipse bundles have different version numbers for each bundle and I've to check the repository to find the according number.. Is there an easier way?

**Comment by cdietrich** [comment]
i dont know
if you can reuse what sebastian has added to xtext.util at
https://github.com/eclipse-xtext/xtext/pull/3293

**Comment by szarnekow** [comment]
> i dont know if you can reuse what sebastian has added to xtext.util at [eclipse-xtext/xtext#3293](https://github.com/eclipse-xtext/xtext/pull/3293)

It has some hardcoded assumptions about Xtext itself, but generally speaking it could serve as a blueprint for mwe2, too.

**Comment by mehmet-karaman** [comment]
This task is done. I am closing this issue ticket.
